### ISSUE TITLE
Sydney ELB DNS TTL doesn't look correct and will cause connection issues

### ISSUE THREAD

**Issue by techmanmike** [SumoLogic/sumologic-net-appenders#10]
The SumoLogic .NET appenders rely on DNS which doesn't look correct for Sydney AU (I could be wrong, as I am no DNS expert).

Windows will cache the DNS entry for the TTL which is 24 hours for "collectors.au.sumologic.com" but if the number of machines in this ELB scales down, then that IP will no longer be valid and there will be a connection failure (which the NLog Sumologic code doesn't handle correctly - logged as a seperate issue).  If this is by design then should we have this enabled?  https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.enablednsroundrobin(v=vs.110).aspx

![pasted image at 2016_08_04 04_13 pm](https://cloud.githubusercontent.com/assets/1566245/17506539/ebfd600a-5e4c-11e6-8781-bf7bad60505a.png)

**Comment by latkin** [comment]
Hi Mike, thanks for opening the issue. I'm no DNS expert either, but in my view I wouldn't want the addition of a log appender to alter app-level DNS settings unexpectedly.

Are you experiencing issues in production or is this a theoretical problem?
