### ISSUE TITLE
SumoLogic.Logging.Serilog -> Serilog 3.0.* Dependency Issue

### ISSUE THREAD

**Issue by vermiceli** [SumoLogic/sumologic-net-appenders#120]
> warning NU1608: Detected package version outside of dependency constraint: SumoLogic.Logging.Serilog 1.0.1.5 requires Serilog (>= 2.0.0 && < 3.0.0) but version Serilog 3.0.1 was resolved.

I'm seeing this warning when installing the latest version of `Serilog`.  Is there a planned update to the `SumoLogic.Logging.Serilog` package to allow the latest Serilog?

**Comment by vermiceli** [comment]
I see that #119 addresses this issue.  Will that be merged?

**Comment by JoshGlue** [comment]
@rnishtala-sumo Will PR #119 be merged?

**Comment by wdolek** [comment]
#119 has been merged and new packages published to NuGet; this issue can be closed as well 🥳
