### ISSUE TITLE
Separate package for SumoLogic.Logging.Common

### ISSUE THREAD

**Issue by shatl** [SumoLogic/sumologic-net-appenders#22]
Hello guys,
Would be great to have a separate package for SumoLogic.Logging.Common, so I use it in custom sinks.

Thanks

**Comment by TerribleDev** [comment]
@shatl https://github.com/billpratt/serilog-sinks-sumologic

**Comment by shatl** [comment]
Thanks @TerribleDev

**Comment by TerribleDev** [comment]
@latkin @shatl I believe this issue can now be closed

**Comment by latkin** [comment]
https://www.nuget.org/packages/SumoLogic.Logging.Common/
