### ISSUE TITLE
SumoLogic sending a single log message as multiple messages

### ISSUE THREAD

**Issue by fractal9000** [SumoLogic/sumologic-net-appenders#32]
This is my reproduced sample code:

        [TestMethod]
        public void Should_log_to_SumoLogic()
        {
            List<string> didNumbers = new List<string>();
            for (int i = 0; i<=25; i++)
            {
                didNumbers.Add("T"+i.ToString("D3")); 
            }
            string message =
                "Sending request to genereate and send all reports for today for the following doctor id numbers: \r\n" +
                string.Join(", \r\n", didNumbers.ToArray());

            Console.WriteLine(message);
            _log4netLogger.Info(message);
        }

It works just fine for 25 numbers.
If I up it to 300 numbers, it fails -- i.e. I will now get 301 messages logged in SumoLogic. See attached images.

I emailed this to SumoLogic support who said the problem resides in the log4net.appender.

![working_1_record](https://cloud.githubusercontent.com/assets/26390922/23871389/897bcb3e-0800-11e7-8beb-6263018d79db.png)

![not_working_300_records](https://cloud.githubusercontent.com/assets/26390922/23871375/79c0f2dc-0800-11e7-98fb-18cde112a631.PNG)

)
Thanks.

Below is my config. BTW, I have used console and file appenders without any problems in the display output.

    <log4net debug="false">
        <appender name="SumoLogicAppender" type="SumoLogic.Logging.Log4Net.SumoLogicAppender, SumoLogic.Logging.Log4Net">
            <layout type="log4net.Layout.PatternLayout">
                <conversionPattern value="%date ThreadId=%thread Level=%level Logger=%logger Message='%message' %newline %newline%exception" />
            </layout>
            <Url value="BLAH" />

            
            <SourceName value="CmmSumoLogicAppender" />
            <UseConsoleLog value="true" />
        </appender>

        <appender name="BufferedSumoLogicAppender" type="SumoLogic.Logging.Log4Net.BufferedSumoLogicAppender, SumoLogic.Logging.Log4Net">
            <layout type="log4net.Layout.PatternLayout">
                <conversionPattern value="%date ThreadId=%thread Level=%level Logger=%logger Message='%message' %newline %newline%exception" />
            </layout>
            <Url value="BLAH" />
            
            <SourceName value="CmmBufferedSumoLogicAppender" />
            <ConnectionTimeout value="30000" />
            <RetryInterval value="5000" />
            <MessagesPerRequest value="10" />
            <MaxFlushInterval value="1000" />
            <FlushingAccuracy value="250" />
            <MaxQueueSizeBytes value="1000000" />
            <UseConsoleLog value="true" />
        </appender>

        <root>
            <level value="DEBUG" />
            <appender-ref ref="SumoLogicAppender" />
            
        </root>
    </log4net>

**Comment by duchatran** [comment]
What if you config the Sumo HTTP source to treat each request as a single message, would that work? Also I suspect the Multiline processing might be doing something here, try unchecking that?

**Comment by fractal9000** [comment]
I noticed the problem has gone away.
SumoLogic Support had said it wasn't their problem and sent me here.
but a few days ago, I looked at my logs and they are now displaying properly.

**Comment by latkin** [comment]
Make sure your Sumo Logic source has appropriate multi-line settings. If left on the default of "auto-detect", results can be hard to predict sometimes.

If the system sees a small number of lines it might group them all together because it doesn't have much to go off of. If it sees hundreds of lines that look like `TNNN` then it will assume this is what individual message look like, and split it up accordingly.

For your case it would probably be appropriate to set a multi-line boundary expression like `^\d{4}-\d{2}-\d{2}.*` so that messages are split at the timestamps.
