### ISSUE TITLE
BufferedSumoLogicAppender

### ISSUE THREAD

**Issue by ischyrus** [SumoLogic/sumologic-net-appenders#37]
I'm using ASP.NET Core, .NET Core, and log4net.

When I use the BufferedSumoLogicAppender I am not seeing all of the entries I'm logging appearing. (I do see the entries being made by Microsoft.AspNetCore.Hosting.Internal.WebHost) However, if I switch the config to using SumoLogicAppender all of them appear.

I'm not sure if I have something I'm overlooking or if this is an issue with the buffered appender.

```
<?xml version="1.0" encoding="utf-8" ?>
<log4net>
  <appender name="RollingFile" type="log4net.Appender.FileAppender">
    <file value="./logs/app.log" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%-5p %d{hh:mm:ss} %message%newline" />
    </layout>
  </appender>
  <appender name="SumoLogicAppender" type="SumoLogic.Logging.Log4Net.SumoLogicAppender, SumoLogic.Logging.Log4Net">
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date [%thread] %-5level %logger - %message%newline"/>
    </layout>
    <Url value="[Myendpoint]" />
    <ConnectionTimeout value="30000" />
    <!-- in milliseconds -->
    <SourceName value="DigestionDev" />
    <UseConsoleLog value="true" />
  </appender>
  <appender name="BufferedSumoLogicAppender" type="SumoLogic.Logging.Log4Net.BufferedSumoLogicAppender, SumoLogic.Logging.Log4Net">
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date [%thread] %-5level %logger - %message%newline"/>
    </layout>
    <Url value="[myendpoint]" />
    <SourceName value="DigestionDev" />
    <ConnectionTimeout value="30000" />
    <RetryInterval value="5000" />
    <MessagesPerRequest value="25" />
    <MaxFlushInterval value="10000" />
    <FlushingAccuracy value="250" />
    <MaxQueueSizeBytes value="500000" />
    <UseConsoleLog value="true" />
  </appender>
  <root>
    <level value="ALL" />
    <appender-ref ref="RollingFile" />
  
	  <!--<appender-ref ref="SumoLogicAppender"/>-->
	  <appender-ref ref="BufferedSumoLogicAppender"/>
  </root>
</log4net>
```

**Comment by latkin** [comment]
Hi @ischyrus, is it possible to create a minimal C# example that shows the issue?

**Comment by ischyrus** [comment]
[SumoExample.zip](https://github.com/SumoLogic/sumologic-net-appenders/files/1016327/SumoExample.zip)

Attached is a simple example. You will need to update the log4net.config to have your Collector URL and SourceName.

**Comment by ischyrus** [comment]
Oh, and comment BufferedSumoLogicAppender and uncomment SumoLogicAppender to see it working.

**Comment by bin3377** [comment]
By investigating it, looks like the problem is log4net configuration. Somehow multiple appender instances were created under your sample. (See attached updated project with some debug trace)
```
BufferedSumoLogicAppender ctor 31
BufferedSumoLogicAppender - Initialize flusher 31
```
So log lines are enqueued to different Appender instances but only one of them are actually send out through HTTP.

I created a SumoTest project with single instance of appender with same setting and it works.
You may need to figure out a way to configure it correctly in your ASP core.NET app. This post may be helpful: https://stackify.com/making-log4net-net-core-work/

**Comment by ischyrus** [comment]
I got it working. I simply removed the SumoLogicAppender entirely and kept the BufferedSumoLogicAppender. 

It's possible that part of the problem was that it was not flushing out as frequently as I thought\expected.
