### ISSUE TITLE
Error while using new 1.0.0.5 version with lambda function.

### ISSUE THREAD

**Issue by spparekh** [SumoLogic/sumologic-net-appenders#44]
Error : Error loading extensions: SumoLogic.Logging.NLog ---> System.IO.FileNotFoundException: Could not load file or assembly 'SumoLogic.Logging.NLog, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Used : Sumologic.Logging.Nlog 1.0.0.5 (for .Net Standard 1.6.0)

Attached: 
Attached Message from Lambda logs.
[CloudWatchLog.txt](https://github.com/SumoLogic/sumologic-net-appenders/files/1125825/CloudWatchLog.txt)

Attached dependencies included in project.
![dependecies included](https://user-images.githubusercontent.com/26581339/27881897-65bcc3b4-6198-11e7-9d39-468e0c62d9ef.jpg)

NLog.config
[Nlog.txt](https://github.com/SumoLogic/sumologic-net-appenders/files/1125840/Nlog.txt)

**Comment by TerribleDev** [comment]
Sounds to me like you are just missing the dll in your zip of files to lambda.

**Comment by spparekh** [comment]
Hi Double checked. Both dll are bundled in zip file and part of release folder. Also exported lambda function package which also contains both of above dll.  

Please let me know if we have any working sample for using Sumologic.Logging.Nlog and .NetCore 1.0

**Comment by TerribleDev** [comment]
@spparekh there is a sample [in the repository](https://github.com/SumoLogic/sumologic-net-appenders/tree/master/SumoLogic.Logging.NLog.Example). We're also using `1.0.0.5` in a docker container.  Have you considered contacting aws? 

Just out of curiosity what does the filesystem inside your zip look like?

**Comment by TerribleDev** [comment]
The fact that you have `the system cannot find the file specified.` in your error message would indicate the filesystem inside of your zip is not correct, or is not setup in a way that will make the dll's discover-able.

**Comment by latkin** [comment]
@spparekh were you able to investigate further? Is the issue still occuring?
