### ISSUE TITLE
Support for SourceCategory and SourceHost in appender config

### ISSUE THREAD

**Issue by latkin** [SumoLogic/sumologic-net-appenders#46]
Somebody logged an issue for our Java appenders, requesting configurable support for setting SourceCategory and SourceHost, similar to how SourceName can currently be set. https://github.com/SumoLogic/sumologic-log4j2-appender/issues/4

This is a reasonable request, so filing it here too.

**Comment by TerribleDev** [comment]
I volunteer as tribute 😝

**Comment by latkin** [comment]
@TerribleDev I have an internal dev who can take it. If you really want to that's great though. What do you think?

**Comment by TerribleDev** [comment]
@latkin seems pretty straight forward. Take in the new variables, if they are not empty strings add the [headers documented here](https://help.sumologic.com/Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Data-to-an-HTTP-Source).

If you want this done in less than 2 weeks, then get your dev on it. However, I'm happy to get this done I may take a little longer as I am currently in the UK, and not in my USA office.

**Comment by latkin** [comment]
I have someone available ~now so I'll go for that. Enjoy 🇬🇧  🍵

**Comment by rvmiller89** [comment]
Added in https://github.com/SumoLogic/sumologic-net-appenders/pull/48
