### ISSUE TITLE
Question: Will this work for a .net core 2.0 application?

### ISSUE THREAD

**Issue by sarchibald-mdsol** [SumoLogic/sumologic-net-appenders#50]
If not, are you aware of any other NLog/Sumo Logic appenders/targets?

**Comment by TerribleDev** [comment]
We target `netstandard1.5` which is compatible with `netcoreapp2.0` so in short. These libraries are binary compatible with net core 2.0. However if there are breakages in NLog,log4net in 2.0 those will have to be addressed with the NLog/Log4Net team

**Comment by sarchibald-mdsol** [comment]
Thanks! I'll be trying it out in the next day or two.

⁣Sent from TypeApp ​
