### ISSUE TITLE
Make an ILogger Implementation

### ISSUE THREAD

**Issue by TerribleDev** [SumoLogic/sumologic-net-appenders#51]
We should make an implementation that works with netcore's ILogger interface so people don't have to use NLog/Log4Net but use the simple logger inside aspnet core.

**Comment by latkin** [comment]
Sounds reasonable, if you are willing to drive the design I am happy to help with review.

**Comment by TerribleDev** [comment]
@latkin I have this work in flight, just been on hold due to the holiday season and me working for a big e-comm

**Comment by kirmak** [comment]
Any news on this? I would be very helpful :)

**Comment by TerribleDev** [comment]
Hi, I have a working implementation. The branch needs some work before a PR is cut. Tbh, I kinda forgot about it. I'll resurrect the work, and I'll try to have something end of this week.

**Comment by TerribleDev** [comment]
This was the half baked implementation https://github.com/SumoLogic/sumologic-net-appenders/pull/59

**Comment by kirmak** [comment]
Thanks a lot!, Yes, I saw #59, but there is disappointing comment *do not merge*, so I decided to ask :)

**Comment by bin3377** [comment]
addressed in https://github.com/SumoLogic/sumologic-net-appenders/pull/75
Need more time on UT and some tweak, but it's a smoking version at least

**Comment by bin3377** [comment]
included in https://github.com/SumoLogic/sumologic-net-appenders/releases/tag/1.0.1.1
