### ISSUE TITLE
No console log in SumoLogic.Logging.Log4Net because SumoLogic.Logging.Common targets .NET Standard 1.1

### ISSUE THREAD

**Issue by bdrupieski** [SumoLogic/sumologic-net-appenders#52]
In the `ActivateConsoleLog` method of `BufferedSumoLogicAppender` and `SumoLogicAppender` in SumoLogic.Logging.Log4Net, if the project is not compiled with `netfull`, `DummyLog` is used instead of `ConsoleLog`. This is unexpected and makes it hard to figure out what's going on. 

The project SumoLogic.Logging.Log4Net targets .NET Standard 1.3 and has access to System.Console. `ConsoleLog` is in SumoLogic.Logging.Common which targets .NET Standard 1.1 and does not have access to System.Console, so it's only compiled with `netfull`. 

Is there a reason why SumoLogic.Logging.Common targets .NET Standard 1.1? Since SumoLogic.Logging.Log4Net targets .NET Standard 1.3, could SumoLogic.Logging.Common also target 1.3 so that the `ActivateConsoleLog` method uses `ConsoleLog`?

**Comment by TerribleDev** [comment]
I think it was just a case of we didn't know console was in 1.3. IMO Increasing to 1.3 is acceptable. Submit a pr?

**Comment by bdrupieski** [comment]
OK, I'll submit a PR sometime this week. Thanks.
