### ISSUE TITLE
.NETStandard 2.0 support?

### ISSUE THREAD

**Issue by hkf57** [SumoLogic/sumologic-net-appenders#60]
Currently for .NET Standard 2.0 projects (including .net core 2.0+), the package is not able to be used due to conflicting dependencies (Package requires NLog >5.0.0-beta09 and NLog.Web.AspNetCore requires NLog.Extensions.Logging and NLog >= 4.5.0-rc02 && < 5.0.0)

This can be resolved if the .NET Standard 2.0 targets can be changed to allow for >=4.5.0-rc02.

**Comment by TerribleDev** [comment]
it seems like all the nlog 5.0.0 packages have been ~~quietly~~ [link to tweet](https://twitter.com/NLogOfficial/status/943256082104901632) de-listed on nuget. I'll drop a PR shortly to target 4.5.0-rc02

**Comment by PeymanGhadiri** [comment]
@TerribleDev  When will this be released?

**Comment by TerribleDev** [comment]
@PeymanGhadiri that would be a question for @latkin 

@latkin it seems this still targets nlog 5. From what I can tell #61 has yet to be released. Any updates?

**Comment by hkf57** [comment]
@TerribleDev #61 has definitely been released. I was able to pull the latest off nuget ~2 months ago.

**Comment by PeymanGhadiri** [comment]
@hkf57 I can't see the latest release which includes #61.
This is what I get in nuget
![image](https://user-images.githubusercontent.com/313392/36648797-0927e814-1aec-11e8-9a28-98cd8ef97fca.png)

Could you please advise how to get the that?

**Comment by latkin** [comment]
Last release on Nuget is definitely from before that PR was merged. Sorry about that, just an oversight that I didn't get to publishing a new one. 🤦‍♂️  

Will try to get an update out soon, thanks for the reminders everyone.

**Comment by latkin** [comment]
New release is up on Nuget (might be a bit before it fully propagates)

https://github.com/SumoLogic/sumologic-net-appenders/releases/tag/1.0.0.7

**Comment by selsig** [comment]
Now that this has been updated, is the nlog package still supposed to be a prerelease? It's also got a dependency on SumoLogic.Logging.Common (>= 1.0.0.7-beta1) which doesn't exist so causes a build warning.

**Comment by latkin** [comment]
@selsig NLog appender is supposed to remain beta for now since the underlying NLog libs are still pre-release. However it's surely a goof on my side that it's depending on phantom SumoLogic.Logging.Common 1.0.0.7-beta1. Let me take a look and see if I can fix that.

**Comment by latkin** [comment]
@selsig I've opened an issue for this https://github.com/SumoLogic/sumologic-net-appenders/issues/62

@TerribleDev any chance you would be able to take a look at a fix for this?
