### ISSUE TITLE
Packaging for NLog appender is setting "beta" version for Common

### ISSUE THREAD

**Issue by latkin** [SumoLogic/sumologic-net-appenders#62]
The NLog appender is currently packed with the following command:

```
dotnet pack .\SumoLogic.Logging.NLog\SumoLogic.Logging.NLog.csproj --output "$(Convert-Path .)\SumoLogic.Logging.Nuget" --configuration Release /p:Version=$fin_ver-beta1
```

This appears to be causing the full dependency chain to get tagged with `-beta1` package version, including SumoLogic.Logging.Common. The goal is for only the NLog portion to be tagged as beta.

![image](https://user-images.githubusercontent.com/5943573/36745109-66149272-1ba3-11e8-9ca8-4f96f8f64eb5.png)

**Comment by selsig** [comment]
I've not done much nuget packaging but would the following work?

Change pack command to:

dotnet pack .\SumoLogic.Logging.NLog\SumoLogic.Logging.NLog.csproj --output "$(Convert-Path .)\SumoLogic.Logging.Nuget" --configuration Release /p:VersionPrefix=$fin_ver

Change SumoLogic.Logging.NLog.csproj to include:

  <PropertyGroup>
    <VersionSuffix>beta1</VersionSuffix>
  </PropertyGroup>

**Comment by latkin** [comment]
Seems reasonable. So many magic msbuild properties...

If you can try it out and confirm that it works then I'd be happy to take a PR with that change.
