### ISSUE TITLE
NLog appender not working with .NET Framework 4.5.2

### ISSUE THREAD

**Issue by catalintomescu** [SumoLogic/sumologic-net-appenders#66]
I added NLog 4.5.6 and SumoLogic.Logging.NLog 1.0.0.7 to an existing Web API project targeting .NET Framework 4.5.2 but the SumoLogic appender throws an exception Exception thrown: 'System.Net.Http.HttpRequestException' in SumoLogic.Logging.Common.dll
Are there any knows issues with .NET Framework 4.5.2?

**Comment by TerribleDev** [comment]
Are you sure you are not running into a TLS issue with your app? Unless you are on 4.6 or higher your app will try to use older versions of TLS that sumologic no longer supports. [This comment](https://github.com/SumoLogic/sumologic-net-appenders/issues/65#issuecomment-402454098) has a few ways in which you can make sure you are using supported versions of TLS.

**Comment by snakefoot** [comment]
@catalintomescu Can you show the entire callstack of the exception?

**Comment by catalintomescu** [comment]
@TerribleDev Following the instructions to configure ServicePointManager.SecurityProtocol resolved the problem. Thanks!
