### ISSUE TITLE
nLog Appender Configuration documentation does not include timestamp

### ISSUE THREAD

**Issue by ermeaney** [SumoLogic/sumologic-net-appenders#8]
This is only a documentation problem, but I got caught with it while working on a demonstration with some guys from SumoLogic.

In the read me, you have the targets setup like this:
<target name="bufferedSumoLogic" type="BufferedSumoLogicTarget" layout="${LEVEL}, ${message}">

But that does not include the timestamps, hence that became a problem. You should include something like this:

<target name="bufferedSumoLogic" type="BufferedSumoLogicTarget" layout="${longdate}, ${LEVEL}, ${message}">

In the examples, just to make it clear that it needs to be included in order for Sumo to extract it.

**Comment by bin3377** [comment]
@ermeaney Thanks for your feedback. but looks like you missing the part after 'this:'? Can you help to specific it?

**Comment by ermeaney** [comment]
Sorry, not sure what happened there.

Currently on a mobile, but what I was trying  to say was in the nLog config example, the layout is missing a date field, which was why I was not getting the date sent to the collector.

Once I fixed that in my configuration, everything worked as expected. So, I am suggesting changing the example configuration for nLog to include that.
