### ISSUE TITLE
OperationCanceledException bubble up to app level

### ISSUE THREAD

**Issue by zakbar** [SumoLogic/sumologic-net-appenders#83]
I have been experiencing issue with sumologic serilog sink, where OperationCanceledException being bubbled up to the app level. This exception is thrown by HttpClient when it can't reach the destination URL over retries. 

After digging into the code, I've noticed that we did modification on following line. https://github.com/SumoLogic/sumologic-net-appenders/blob/master/SumoLogic.Logging.Common/Sender/BufferFlushingTask.cs#L128

```
        [SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Justification = "Exception unknown at compile time.")]
        public Task Run()
        {
            if (this.NeedsFlushing())
            {
                this.IsFlushing = true;
                try
                {
                    return this.FlushAndSend();
                }
                catch (Exception ex)
                {
                    if (this.Log.IsWarnEnabled)
                    {
                        this.Log.Warn("Exception while attempting to flush and send, Exception: " + ex.Message);
                    }
                }
            }

            this.IsFlushing = false;
            return CompletedTask;
        }
```

The try-catch in here is not going to work, since we're returning Task straight away from `this.FlushAndSend();`. This means all exception occurred after this point will be pushed up and can go to the app level (when observed).

Version used: 
SumoLogic.Logging.Serilog 1.0.1.1
SumoLogic.Logging.Common 1.0.1.1

**Comment by snakefoot** [comment]
Created PR #89 to resolve this  (Bug introduced in ver. 1.0.0.11)

**Comment by snakefoot** [comment]
@zakbar Are you using ver. 1.0.1.1 that includes #78 ?

**Comment by zakbar** [comment]
Yes, I am using 1.0.1.1
