### ISSUE TITLE
SumoLogic NLog appender does retry correctly

### ISSUE THREAD

**Issue by techmanmike** [SumoLogic/sumologic-net-appenders#9]
When calling PostAsync and there is a Timeout on connecting/sending the data it will throw a AggregateException which is caught and then the sumo appender throws the InnerException which is correct.

However, this inner exception should then be caught by the Send() method, but it only catches "IOException" and it could be HttpRequestException or WebException or any other number of exceptions.

So if it can't connect, then it doesn't retry and the messages are dropped.

**Comment by latkin** [comment]
Thanks for noticing this, I've submitted a fix that additionally handles those exception types you mentioned here.

**Comment by latkin** [comment]
cc @techmanmike
